### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [bjorn-pederson-ohsu/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by bjorn-pederson-ohsu** [comment]
Bjorn Pederson is an Instructional Designer and comes with a backgorund of providing online workforce development materials for Direct Support Professionals, as well as working and developing technology skills for pre-service teachers. Much of his work is centered around facilitating and affording meaningful online learning experiences.
