### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by hubyeti** [bjorn-pederson-ohsu/github-for-developers-7#4]
We need to create a .gitignore file and add .log files.

**Comment by bjorn-pederson-ohsu** [comment]
#Untracked files
Thumbs.db

#BDK01-1_SCORM12.zip
#BDK01-1_Tin_Can.zip
BDK01-1_SCORM12.zip
BDK01-1_Tin_Can.zip

#BDK01-2_SCORM12.zip
#BDK01-2_Tin_Can.zip
BDK01-2_SCORM12.zip
BDK01-2_Tin_Can.zip

#BDK01-3_SCORM12.zip
#BDK01-3_Tin_Can.zip
BDK01-3_SCORM12.zip
BDK01-3_Tin_Can.zip

BDK01_exercises.zip

**Comment by bjorn-pederson-ohsu** [comment]
first .gitignore file
